---
title: "tweedy_gist"
output: word_document
---


```{r echo = FALSE, warning = FALSE, message = FALSE, results = "hide", fig.keep = 'none'}
source("/Users/laura.ganley001/Documents/R_Projects/SEM/variable_workup.R")

library(lubridate)
library(imputeTS)
library(tseries)
library(forecast)
library(ggplot2)
library(ggmap)
library(maptools)
library(maps)
library(geosphere)
library(grid)
library(TSA)
library(ggsn)
library(brms)
library(piecewiseSEM)
```

```{r}
abund.tweed <- glmer(eg.abund ~ pop.est + MTZ + MTZ*CCBStrat + (1|Year),  
                     family=tweedie(var.power=1.1, link.power=0), data = all.data)

```

```{r}
##Fake model 1
k_fit_psem <- psem(
  glmer(eg.abund ~ pop.est + MTZ + MTZ * CCBStrat + (1|Year), 
        family=tweedie(var.power=1.1, link.power=0), data = all.data), ## include random effect of Year because the population estimate was measured on a yearly level.
  lme(CCBStrat ~ RegWindDirec * RegWindSpd, random = ~1|Year, data = all.data),
  lme(MTZ.sq ~ CCBStrat + RegWindDirec * RegWindSpd, random = ~1|Year, data = all.data),
  lme(RegWindSpd ~ NAO + RegWindDirec, random = ~1|Year, data = all.data),
  lme(RegWindDirec ~ NAO, random = ~1|Year, data = all.data),
  data = all.data
)
```